### ISSUE TITLE
Matrix multiplication in CVXPY 1.1

### ISSUE THREAD

**Issue by JohnyVolz** [kit-cel/lecture-examples#11]
Hi,
in the Jupyter-Notebook "DMC_Capacity.ipynb" from the lecture CC_GBC, i get the folowing hint:
```
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

```
I think this commes from the following line of code:
`objective = cp.Maximize(np.sum(Ptilde,axis=0)*px + cp.sum(cp.entr(P*px))/np.log(2.0))`

and needs to be changed to:
`objective = cp.Maximize(np.sum(Ptilde,axis=0)`@` px + cp.sum(cp.entr(P `@`px))/np.log(2.0))`

Best regards
Johny Volz

**Comment by lschmalen** [comment]
Has been fixed with the latest commit
